<?php
$this->assign('title', $area->display_name);
$categories = ['COR' => 'Corretivas', 'PRE' => 'Preventivas', 'MEL' => 'Melhorias'];
$cardRoute = $area->source_code ? ['_name' => 'pcm-sector', 'code' => $area->source_code] : ['_name' => 'pcm-orders'];
$chartPayload = ['status' => $dashboard['status'], 'maintenance' => array_map(static function (array $row) use ($categories): array { $row['label'] = $categories[$row['key']] ?? $row['label']; return $row; }, $dashboard['maintenanceProfile']), 'equipment' => $dashboard['equipment'], 'services' => $dashboard['services'], 'costCenters' => $dashboard['costCenters']];
$this->Html->script(['chart.umd.min', 'pcm-sector', 'pcm-history'], ['block' => true]);
?>
<header class="pcm-page-header"><div><p class="pcm-eyebrow">PCM | SETOR</p><h1><?= h($area->display_name) ?></h1><p class="pcm-updated"><?php if ($area->source_code): ?>Código: <strong><?= h($area->source_code) ?></strong> <span aria-hidden="true">•</span><?php endif; ?> <?= $this->element('pcm_updated_at', compact('lastUpdatedAt')) ?></p></div></header>
<?php if ($currentImport === null): ?><div class="alert alert-light border shadow-sm">Nenhum relatório foi importado com sucesso.</div><?php endif; ?>
<?= $this->element('pcm_indicator_cards', ['indicators' => $indicators, 'comparison' => $comparison ?? null, 'cardRoute' => $cardRoute, 'filters' => $filters]) ?>
<section class="pcm-panel pcm-filter-panel mt-4"><div class="pcm-panel-heading"><h2><?= $area->source_code ? 'Filtros do setor' : 'Filtros do relatório' ?></h2><p>Indicadores e gráficos excluem canceladas. A listagem mantém canceladas para consulta e auditoria.</p></div>
<?= $this->Form->create(null, ['type' => 'get', 'class' => 'pcm-filter-form']) ?>
<div class="row g-3 pcm-filter-main-row"><div class="col-12 col-md-6 col-xl"><?= $this->Form->control('status', ['label' => 'Status (inclui auditoria)', 'empty' => 'Todos', 'options' => array_combine(\App\Service\SectorDashboardService::STATUSES, \App\Service\SectorDashboardService::STATUSES), 'value' => $filters['status'] ?? '']) ?></div>
<?php foreach (['equipment' => 'Equipamento/Bem', 'service' => 'Serviço', 'service_name' => 'Nome Serviço', 'area' => 'Área Manut.', 'cost_center' => 'Centro de custo', 'maintenance_type' => 'Tipo Manut. TOTVS'] as $key => $label): ?><div class="col-12 col-md-6 col-xl"><?= $this->Form->control($key, ['label' => $label, 'empty' => 'Todos', 'options' => array_column($dashboard['options'][$key], 'label', 'value'), 'value' => $filters[$key] ?? '']) ?></div><?php endforeach; ?></div>
<div class="mt-3"><?= $this->Form->control('classification', ['label' => 'Classificação do serviço', 'empty' => 'Todas', 'options' => \App\Service\PcmServiceClassifier::LABELS, 'value' => $filters['classification'] ?? '']) ?></div>
<div class="row g-3 align-items-end pcm-filter-search-row"><div class="col-12 col-lg"><?= $this->Form->control('q', ['label' => 'Pesquisar OS, bem ou serviço', 'value' => $filters['q'] ?? '', 'placeholder' => 'Digite número, código ou nome']) ?></div><div class="col-12 col-sm-auto"><div class="pcm-filter-actions"><button class="btn pcm-primary-action">Aplicar</button><?= $this->Html->link('Limpar', $cardRoute, ['class' => 'btn pcm-secondary-action']) ?></div></div></div><?= $this->Form->end() ?></section>

<section class="pcm-dashboard-section"><div class="pcm-section-title"><p>VISÃO DAS OS</p><h2>Situação da carteira</h2></div><div class="row g-4"><div class="col-lg-6"><div class="pcm-chart-card"><h3>Distribuição por status</h3><p>Quantidade e participação no conjunto filtrado.</p><div class="pcm-chart-wrap"><canvas id="statusChart"></canvas></div></div></div><div class="col-lg-6"><div class="pcm-chart-card"><h3>Perfil de manutenção</h3><p>Campo Tipo Manut. do TOTVS, somente OS não canceladas.</p><div class="pcm-chart-wrap"><canvas id="maintenanceChart"></canvas></div></div></div></div></section>
<section class="pcm-dashboard-section"><div class="pcm-section-title"><p>EQUIPAMENTOS E SERVIÇOS</p><h2>Onde a demanda se concentra</h2></div><div class="row g-4"><div class="col-xl-6"><div class="pcm-chart-card pcm-chart-card-tall"><h3>Top 10 equipamentos com mais OS</h3><p>Código e nome do bem; cadastros genéricos podem aparecer.</p><div class="pcm-chart-wrap"><canvas id="equipmentChart"></canvas></div></div></div><div class="col-xl-6"><div class="pcm-chart-card pcm-chart-card-tall"><h3>Top 10 serviços mais recorrentes</h3><p>Volume pelo Nome Serviço do TOTVS.</p><div class="pcm-chart-wrap"><canvas id="servicesChart"></canvas></div></div></div><div class="col-12"><div class="pcm-chart-card"><h3>OS por centro de custo</h3><p>Ranking por quantidade; não representa custo financeiro.</p><div class="pcm-chart-wrap"><canvas id="costCentersChart"></canvas></div></div></div></div></section>
<section class="pcm-dashboard-section"><div class="pcm-section-title"><p>PONTOS DE ATENÇÃO</p><h2>Sinais seguros do snapshot atual</h2></div><div class="row g-3">
<?php foreach ([['Em aberto', $dashboard['indicators']['open'], 'status', 'EM ABERTO'], ['Canceladas — auditoria', $dashboard['attention']['cancelled'], 'status', 'CANCELADA'], ['Sem início real informado', $dashboard['attention']['missingStart'], '', '']] as [$label, $value, $key, $filter]): ?><div class="col-md-4"><div class="pcm-attention-card"><span><?= h($label) ?></span><strong><?= number_format((int)$value, 0, ',', '.') ?></strong><?php if ($key): ?><a href="?<?= h(http_build_query([$key => $filter])) ?>">Investigar OS</a><?php endif; ?></div></div><?php endforeach; ?>
<?php foreach ([['Equipamento mais recorrente', $dashboard['attention']['topEquipment'], 'equipment'], ['Serviço mais recorrente', $dashboard['attention']['topService'], 'service']] as [$label, $item, $key]): ?><div class="col-md-6"><div class="pcm-attention-card"><span><?= h($label) ?></span><strong class="pcm-attention-name"><?= h($item['label'] ?? '—') ?></strong><small><?= $item ? number_format($item['quantity'], 0, ',', '.') . ' OS · ' . number_format($item['percentage'], 1, ',', '.') . '%' : 'Sem dados' ?></small><?php if ($item): ?><a href="?<?= h(http_build_query([$key => $item['key']])) ?>">Investigar OS</a><?php endif; ?></div></div><?php endforeach; ?>
</div></section>
<section class="pcm-dashboard-section"><div class="pcm-section-title"><h2>Resumo por serviço</h2><p>OS não canceladas da última importação bem-sucedida, respeitando os filtros.</p></div><div class="pcm-panel table-responsive"><table class="table"><thead><tr><th>Serviço / classificação</th><th>Abertas</th><th>Fechadas</th></tr></thead><tbody>
<?php foreach ($dashboard['summary'] as $row): ?><tr><td><?= h($row['label']) ?></td><td><?= number_format($row['open'], 0, ',', '.') ?></td><td><?= number_format($row['completed'], 0, ',', '.') ?></td></tr><?php endforeach; ?>
</tbody></table></div></section>
<section class="pcm-dashboard-section" id="orders"><div class="pcm-section-title"><p>DETALHAMENTO</p><h2>Ordens de Serviço</h2></div><div class="pcm-panel"><div class="table-responsive"><table class="table pcm-orders-table align-middle mb-0"><thead><tr><th><?= $this->Paginator->sort('source_order_number', 'Ordem Serv.') ?></th><th>Bem</th><th><?= $this->Paginator->sort('equipment_name', 'Nome do Bem') ?></th><th><?= $this->Paginator->sort('service_code', 'Serviço') ?></th><th><?= $this->Paginator->sort('service_name', 'Nome Serviço') ?></th><th>Área</th><th><?= $this->Paginator->sort('cost_center_code', 'Centro Custo') ?></th><th><?= $this->Paginator->sort('maintenance_type', 'Tipo Manut.') ?></th><th><?= $this->Paginator->sort('source_situation', 'Situação') ?></th><th><?= $this->Paginator->sort('finished_raw', 'Término') ?></th><th><?= $this->Paginator->sort('general_actual_start', 'Real. Início') ?></th><th><?= $this->Paginator->sort('treated_status', 'Status') ?></th><th></th></tr></thead><tbody>
<?php foreach ($orders as $order): ?><tr><td><strong><?= h($order->source_order_number) ?></strong></td><td><?= h($order->equipment_code ?: '—') ?></td><td><?= h($order->equipment_name ?: '—') ?></td><td><?= h($order->service_code ?: '—') ?></td><td><?= h($order->service_name ?: '—') ?></td><td><?= h($order->maintenance_area_code ?: '—') ?></td><td><?= h($order->cost_center_code ?: '—') ?></td><td><?= h($order->maintenance_type ?: '—') ?></td><td><?= h($order->source_situation ?: '—') ?></td><td><?= h($order->finished_raw ?: '—') ?></td><td><?= h($this->PcmTime->format($order->general_actual_start)) ?></td><td><span class="badge pcm-status-badge"><?= h($order->treated_status) ?></span></td><td><?= $this->Html->link('Ver detalhes', ['_name' => 'pcm-order', 'id' => $order->id], ['class' => 'btn btn-sm btn-outline-primary text-nowrap']) ?></td></tr><?php endforeach; ?><?php if (count($orders) === 0): ?><tr><td colspan="13" class="pcm-empty-table">Nenhuma OS encontrada para os filtros aplicados.</td></tr><?php endif; ?></tbody></table></div>
<?php if (count($orders) > 0): ?><footer class="pcm-pagination"><p><?= $this->Paginator->counter('Página {{page}} de {{pages}} • {{count}} OS') ?></p><nav aria-label="Paginação das Ordens de Serviço"><ul class="pcm-page-list"><?= $this->Paginator->prev('‹ Anterior') ?><?= $this->Paginator->numbers(['modulus' => 5, 'first' => 1, 'last' => 1]) ?><?= $this->Paginator->next('Próxima ›') ?></ul></nav></footer><?php endif; ?></div></section>
<?php if (isset($history)): ?><?= $this->element('pcm_history', compact('history', 'area')) ?><?php endif; ?>
<script type="application/json" id="pcm-chart-data"><?= json_encode($chartPayload, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_UNESCAPED_UNICODE) ?></script>
